displayName=Inventory Count
author=robrichardson13
description=Shows a count of open inventory spaces
tags=inventory,count,slots,overlay
plugins=io.robrichardson.inventorycount.InventoryCountPlugin
build=standard
